version: '3.9'

services:
  primetester:
    container_name: "primetester"
    build:
      context: ..
      dockerfile: ./build/Dockerfile_primes
    restart: on-failure
    environment:
      - HTTP_HOST=${HTTP_HOST}
      - HTTP_PORT=${HTTP_PORT}
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}" 

  integration-tests:
    container_name: "integration-tests"
    build:
      context: ..
      dockerfile: ./build/Dockerfile_tests
    environment:
      - HTTP_HOST=primetester
      - HTTP_PORT=${HTTP_PORT}
    depends_on:
      - "primetester"